### ISSUE TITLE
Use of P(w) in distinctiveness calculation

### ISSUE THREAD

**Issue by roger-mahler** [lejon/PartiallyCollapsedLDA#14]
I'm in the process of implementing a Python-wrapper for PC-LDA to be used in the Welfare state analytics research project. I have a question concerning the distinctiveness calculation [here](https://github.com/lejon/PartiallyCollapsedLDA/blob/ad5370fef106ee7f5fe6cbb9beb6d7b8e5ff8235/src/main/java/cc/mallet/util/LDAUtils.java#L949).

The formula according to [Chung et. a.l 2012] is `Σ p(t|w) ∙ log(p(t|w) / p(t))`, whilst the code implements the formula `Σ p(t|w) ∙ log(p(t|w) / p(w))` i.e. word probability is used instead of topic probability. Is this a bug, or am I missing something?

@MansMeg

**Comment by MansMeg** [comment]
Hi! I need to check this in the paper myself to be sure. Currently, I'm quite busy with paper submission, but later this week I'll check this!

**Comment by lejon** [comment]
Thanks for the heads up Roger! Will check it out when time permits!

**Comment by MansMeg** [comment]
Yes. It looks like a bug in the code. We should supply p_t() instead of p_w() to the function. I guess this is a real bug if the documentation is correct. But it depends what is supplied to the function if we supply p_t to p_w it would still maybe be correct.

Anyway the notation should be fixed/correct. Also we should check that the function uses the correct p_t().

**Comment by lejon** [comment]
Again, many thanks @roger-mahler for the heads up. I have now corrected this in commit https://github.com/lejon/PartiallyCollapsedLDA/commit/fd2b1aff9720a4b2218cc2c748132f0ae6f5811f

Cheers!
